package com.vindya.mini_order_inventory.dto;

import java.math.BigDecimal;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Sales figures for a single product (active orders only)")
public class ProductReportDTO {

    @Schema(description = "Unique product identifier", example = "1")
    private Long productId;
    @Schema(description = "Product name", example = "Laptop")
    private String productName;
    @Schema(description = "Total units sold", example = "12")
    private Long quantitySold;
    @Schema(description = "Total revenue generated by the product", example = "600000.00")
    private BigDecimal totalRevenue;
}